services:
  ducky:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - monguito
    volumes:
      - .:/home/app
  monguito:
    image: mongo
    ports: -"27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pato
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mondo-data: /data/db
volumes:
  mongo-data:
